dateModified: 1755635368
elementSources:
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: '*'
      tableAttributes:
        - status
        - section
        - postDate
        - expiryDate
        - link
      type: native
    -
      key: singles
      type: native
    -
      heading: ''
      key: 'heading:46b20610-7edb-4532-847c-c5cb1d035937'
      type: heading
    -
      heading: Golf
      key: 'heading:d2f94e4e-3040-4858-a6e4-ee2d13c0f149'
      type: heading
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: 'section:b48a4b4d-b14d-4bf3-8c72-1d7dd675978a' # Golf Courses
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - link
      type: native
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: 'section:91b19907-e037-44e3-8e66-2d33aaa46685' # Golf Rounds
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - link
      type: native
    -
      heading: ''
      key: 'heading:cee8176f-2136-4bd2-9dd4-d864862c7b91'
      type: heading
    -
      heading: Music
      key: 'heading:7e3a1b8b-af05-4f1b-8a95-77822fd4f182'
      type: heading
    -
      key: 'section:490d39af-3a89-42de-b5fc-d9072a4d154f' # Music
      type: native
    -
      heading: ''
      key: 'heading:2589f322-f96a-44d9-81f7-d6f21799b8d4'
      type: heading
    -
      heading: Running
      key: 'heading:3c4b12b5-9741-4d32-9812-989344b50955'
      type: heading
    -
      key: 'section:c7381acb-da4c-4ae0-8504-4ba30d7893c2' # Running
      type: native
email:
  fromEmail: kritikpatel22@gmail.com
  fromName: "KP's Music"
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    2a4f3a53-b727-4b1d-be96-fc5046918b98: Running # Running
    9f22f4a9-7071-4014-a78c-3bae8d927814: 'Golf Courses' # Golf Courses
    035aedf7-8fa0-418d-9b49-ca7768a50681: Homepage # Homepage
    91b19907-e037-44e3-8e66-2d33aaa46685: 'Golf Rounds' # Golf Rounds
    490d39af-3a89-42de-b5fc-d9072a4d154f: Music # Music
    681eb003-6205-4314-b36a-ee58a465c8ae: 'Kritik Patel' # Kritik Patel
    3024dcee-b435-41ed-a4c0-b085497f4d68: Homepage # Homepage
    a5720a60-0094-4d7f-9808-23b8bdc8b21b: 'Golf Rounds' # Golf Rounds
    b48a4b4d-b14d-4bf3-8c72-1d7dd675978a: 'Golf Courses' # Golf Courses
    bcdd7152-a5b5-46bd-a1d3-f8d1bbd64472: 'Kritik Patel' # Kritik Patel
    c63bc5e7-9b59-4634-8002-78ddc369444f: 'Main Navigation' # Main Navigation
    c7381acb-da4c-4ae0-8504-4ba30d7893c2: Running # Running
    f9292f8d-4e27-4097-8e21-3292526d888b: Music # Music
plugins:
  navigation:
    edition: standard
    enabled: true
    licenseKey: KDPUV9H8CJR3D5XQIZEPDXEN
    schemaVersion: 2.1.0
system:
  edition: solo
  live: true
  name: 'Kritik Patel'
  retryDuration: null
  schemaVersion: 5.8.0.3
  timeZone: Europe/London
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
